package co.tpcreative.domain.models

enum class EnType {
    IMAGE, VOICE_RECORD, MESSAGE, FORGOT_PASSWORD, NEW_USER, NEW_STORE_FILES_SUBSCRIPTION, SEND_EMAIL, SEND_EMAIL_STORE_FILES_SUBSCRIPTION, SEND_EMAIL_SUCCESSFUL, SEND_EMAIL_ERROR, REFRESH, ADD_EMAIL_TOKEN
}
