package co.tpcreative.domain.models

enum class EnumValidationKey {
    EDIT_TEXT_EMAIL,
    EDIT_PASSWORD,
    EDIT_OLD_PASSWORD,
    EDIT_NEW_PASSWORD,
    EDIT_TEXT_CONFIRM_PASSWORD,
    EDIT_TEXT_PHONE_NUMBER,
    EDIT_TEXT_CODE,
    EDIT_TEXT_CONTENT,
    EDIT_TEXT_SECRET_PIN
}